export const posts = [
  {
    id: 1,
    image: "/Podcast/image/homepage/news/news1.png",
    description: "аудио аппаратура",
    category: "Podcast",
    title: "Setup your own podcast",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris.",
    theme: "business, podcast, startup",
    date: "Sep 14, 2021",
  },
  {
    id: 2,
    image: "/Podcast/image/homepage/news/news2.png",
    description: "девушка в маске рисует на стене",
    category: "Tips & Trick",
    title: "Doodle artwork 101",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris.",
    theme: "art, tips and trick, creative",
    date: "Sep 12, 2021",
  },
  {
    id: 3,
    image: "/Podcast/image/homepage/news/news3.png",
    description: "рамка из листочков и веточек",
    category: "News",
    title: "Mother Nature Taking Over",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris.",
    theme: "nature, news",
    date: "Sep 10, 2021",
  },
  {
    id: 4,
    image: "/Podcast/image/homepage/news/news4.png",
    description: "парень и девушка в наушниках сидят на диване",
    category: "Productivity",
    title: "How to Be Productive",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris.",
    theme: "mindset, productivity",
    date: "Sep 8, 2021",
  },
  {
    id: 5,
    image: "/Podcast/image/homepage/news/news1.png",
    description: "аудио аппаратура",
    category: "Business",
    title: "Setup your own podcast",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris.",
    theme: "business, podcast, startup",
    date: "Sep 14, 2021",
  },
  {
    id: 6,
    image: "/Podcast/image/homepage/news/news2.png",
    description: "девушка в маске рисует на стене",
    category: "News",
    title: "Doodle artwork 101",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minimvel iam, quis nostrud exercitation ullamco laboris.",
    theme: "art, tips and trick, creative",
    date: "Sep 12, 2021",
  },
];

export const categories = [
  "All",
  "Business",
  "News",
  "Tips & Trick",
  "Podcast",
  "Productivity",
];

export const episodes = [
  {
    id: 11,
    subtitle: "Eps. 6",
    title: "Pandemic Becoming Endemic",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.",
    imageUrl: "/Podcast/image/homepage/episodes/episode1.png",
    imageAlt: "на сером фоне на стульях сидят вирусы",
    tags: ["covid-19", "health"],
    time: "46min",
  },
  {
    id: 12,
    subtitle: "Eps. 5",
    title: "Tesla Autopilot Controversy",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.",
    imageUrl: "/Podcast/image/homepage/episodes/episode2.png",
    imageAlt: "машина наклонилась на бок и стоит на двух колесах",
    tags: ["automation", "tech"],
    time: "48min",
  },
  {
    id: 13,
    subtitle: "Eps. 4",
    title: " Women's Rights? Is it alright?",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.",
    imageUrl: "/Podcast/image/homepage/episodes/episode3.png",
    imageAlt: "девушки и парни сидят на полу",
    tags: ["women’s rights"],
    time: "35min",
  },
  {
    id: 14,
    subtitle: "Eps. 3",
    title: "How to Deal with Self–Confidence",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.",
    imageUrl: "/Podcast/image/homepage/episodes/episode4.png",
    imageAlt: "человек в сером облегающем косюие лежит на серой листве",
    tags: ["self-esteem", "health"],
    time: "51min",
  },
  {
    id: 15,
    subtitle: "Eps. 2",
    title: "PType of Social Classes of People",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.",
    imageUrl: "/Podcast/image/homepage/episodes/episode5.png",
    imageAlt: "мужчина в костюме сидит на опрокинутом стуле",
    tags: ["social class", "wealth"],
    time: "38min",
  },
  {
    id: 16,
    subtitle: "Eps. 1",
    title: "Pandemic Becoming Endemic",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.",
    imageUrl: "/Podcast/image/homepage/episodes/episode6.png",
    imageAlt: "лицо девушки, которая держится за свое лицо",
    tags: ["mind-behaviour", "health"],
    time: "42min",
  },
];

export const feedback = [
  {
    id: "nkyWG0rgfF",
    name: "Ann",
    email: "aaa@yandex.ru",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea aspernatur sunt, voluptas corporis, deleniti quasi eaque, voluptate facere veniam officiis animi culpa natus fugiat voluptatibus necessitatibus laborum quidem distinctio ratione! Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: "wz22HBkTby",
    name: "Jack",
    email: "jjj@yandex.ru",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea aspernatur sunt, voluptas corporis, deleniti quasi eaque, voluptate facere veniam officiis animi culpa natus fugiat voluptatibus necessitatibus laborum quidem distinctio ratione! Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: "1At5j18OcS",
    name: "Lucas",
    email: "lll@yandex.ru",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea aspernatur sunt, voluptas corporis, deleniti quasi eaque, voluptate facere veniam officiis animi culpa natus fugiat voluptatibus necessitatibus laborum quidem distinctio ratione! Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: "a91bvRmpQy",
    name: "Emily",
    email: "eee@yandex.ru",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea aspernatur sunt, voluptas corporis, deleniti quasi eaque, voluptate facere veniam officiis animi culpa natus fugiat voluptatibus necessitatibus laborum quidem distinctio ratione! Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    id: "GdEXxea7bL",
    name: "Florence",
    email: "fff@yandex.ru",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea aspernatur sunt, voluptas corporis, deleniti quasi eaque, voluptate facere veniam officiis animi culpa natus fugiat voluptatibus necessitatibus laborum quidem distinctio ratione! Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
];

export const feedbackSliderItems = [
  {
    id: 1,
    text: "Lorem ipsum dolor sit amet consectet piscing elit, sed do eiusmod tempor incidi ut labore et dolore magna aliqua.",
    avatarsrc: "Podcast/image/homepage/sliderfeedback/avatar1.png",
    avataralt: "фото девушки",
    name: "Luna lovegood,",
    sourcesrc: "Podcast/image/homepage/spotify.png",
    sourcealt: "Spotify",
    class: "little",
  },
  {
    id: 2,
    text: "Lorem ipsum dolor sit amet consectet piscing elit, sed do eiusmod tempor incidi ut labore et dolore magna aliqua.",
    avatarsrc: "Podcast/image/homepage/sliderfeedback/avatar2.png",
    avataralt: "фото девушки",
    name: "Emily Blunt,",
    sourcesrc: "Podcast/image/homepage/googlepodcasts.png",
    sourcealt: "Googlepodcasts",
    class: "big",
  },
  {
    id: 3,
    text: "Lorem ipsum dolor sit amet consectet piscing elit, sed do eiusmod tempor incidi ut labore et dolore magna aliqua.",
    avatarsrc: "Podcast/image/homepage/sliderfeedback/avatar3.png",
    avataralt: "фото девушки",
    name: "Mia Winters,",
    sourcesrc: "Podcast/image/homepage/spotify.png",
    sourcealt: "Spotify",
    class: "little",
  },
  {
    id: 4,
    text: "Lorem ipsum dolor sit amet consectet piscing elit, sed do eiusmod tempor incidi ut labore et dolore magna aliqua.",
    avatarsrc: "Podcast/image/homepage/sliderfeedback/avatar1.png",
    avataralt: "фото девушки",
    name: "Luna lovegood,",
    sourcesrc: "Podcast/image/homepage/spotify.png",
    sourcealt: "Spotify",
    class: "little",
  },
  {
    id: 5,
    text: "Lorem ipsum dolor sit amet consectet piscing elit, sed do eiusmod tempor incidi ut labore et dolore magna aliqua.",
    avatarsrc: "Podcast/image/homepage/sliderfeedback/avatar2.png",
    avataralt: "фото девушки",
    name: "Emily Blunt,",
    sourcesrc: "Podcast/image/homepage/googlepodcasts.png",
    sourcealt: "Googlepodcasts",
    class: "big",
  },
  {
    id: 6,
    text: "Lorem ipsum dolor sit amet consectet piscing elit, sed do eiusmod tempor incidi ut labore et dolore magna aliqua.",
    avatarsrc: "Podcast/image/homepage/sliderfeedback/avatar3.png",
    avataralt: "фото девушки",
    name: "Mia Winters,",
    sourcesrc: "Podcast/image/homepage/spotify.png",
    sourcealt: "Spotify",
    class: "little",
  },
];

export const homepageSlides = [
  {
    id: 1,
    imagesrc: "Podcast/image/homepage/slider/slide1.png",
    imagealt: "человеческая фигура на фоне серых листьев",
  },
  {
    id: 2,
    imagesrc: "Podcast/image/homepage/slider/slide2.png",
    imagealt: "девушка закатила глаза и высунула язык",
  },
  {
    id: 3,
    imagesrc: "Podcast/image/homepage/slider/slide3.png",
    imagealt: "девушки и парни сидят на полу",
  },
  {
    id: 4,
    imagesrc: "Podcast/image/homepage/slider/slide1.png",
    imagealt: "человеческая фигура на фоне серых листьев",
  },
  {
    id: 5,
    imagesrc: "Podcast/image/homepage/slider/slide2.png",
    imagealt: "девушка закатила глаза и высунула язык",
  },
  {
    id: 6,
    imagesrc: "Podcast/image/homepage/slider/slide3.png",
    imagealt: "девушки и парни сидят на полу",
  },
];

/*slider about*/
export const sponsor = [
  {
    id: 1,
    imagesrc: "/Podcast/image/about/spotify.png",
    imgalt: "spotify",
    text: "Quis dictum cursus faucibus mattis dignissim. Pellentes que purus in sed sodales in mauris molestie. Eleifend estcon sctetur interdum eu in auctor. Gravida leo et.",
  },
  {
    id: 2,
    imagesrc: "/Podcast/image/about/googlepodcasts.png",
    imgalt: "googlepodcasts",
    text: "Quis dictum cursus faucibus mattis dignissim. Pellentes que purus in sed sodales in mauris molestie. Eleifend estcon sctetur interdum eu in auctor. Gravida leo et.",
  },
  {
    id: 3,
    imagesrc: "/Podcast/image/about/youtube.png",
    imgalt: "youtube",
    text: "Quis dictum cursus faucibus mattis dignissim. Pellentes que purus in sed sodales in mauris molestie. Eleifend estcon sctetur interdum eu in auctor. Gravida leo et.",
  },
  {
    id: 4,
    imagesrc: "/Podcast/image/about/spotify.png",
    imgalt: "spotify",
    text: "Quis dictum cursus faucibus mattis dignissim. Pellentes que purus in sed sodales in mauris molestie. Eleifend estcon sctetur interdum eu in auctor. Gravida leo et.",
  },
  {
    id: 5,
    imagesrc: "/Podcast/image/about/googlepodcasts.png",
    imgalt: "googlepodcasts",
    text: "Quis dictum cursus faucibus mattis dignissim. Pellentes que purus in sed sodales in mauris molestie. Eleifend estcon sctetur interdum eu in auctor. Gravida leo et.",
  },
  {
    id: 6,
    imagesrc: "/Podcast/image/about/youtube.png",
    imgalt: "youtube",
    text: "Quis dictum cursus faucibus mattis dignissim. Pellentes que purus in sed sodales in mauris molestie. Eleifend estcon sctetur interdum eu in auctor. Gravida leo et.",
  },
  {
    id: 7,
    imagesrc: "/Podcast/image/about/spotify.png",
    imgalt: "spotify",
    text: "Quis dictum cursus faucibus mattis dignissim. Pellentes que purus in sed sodales in mauris molestie. Eleifend estcon sctetur interdum eu in auctor. Gravida leo et.",
  },
  {
    id: 8,
    imagesrc: "/Podcast/image/about/googlepodcasts.png",
    imgalt: "googlepodcasts",
    text: "Quis dictum cursus faucibus mattis dignissim. Pellentes que purus in sed sodales in mauris molestie. Eleifend estcon sctetur interdum eu in auctor. Gravida leo et.",
  },
  {
    id: 9,
    imagesrc: "/Podcast/image/about/youtube.png",
    imgalt: "youtube",
    text: "Quis dictum cursus faucibus mattis dignissim. Pellentes que purus in sed sodales in mauris molestie. Eleifend estcon sctetur interdum eu in auctor. Gravida leo et.",
  },
];
